# Generated by Django 4.2 on 2023-05-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='adress',
            new_name='address',
        ),
    ]
